### ISSUE TITLE
ValueError in triplet_formats example

### ISSUE THREAD

**Issue by JFHoelscher** [dekuenstle/cblearn#40]
Occurs both when running `triplet_formats.py` and `triplet_formats.ipynb`.
Python version: 3.9.7
Numpy version: 1.20.3
Stack trace:
<pre><code>
`/home/johannes/miniconda3/envs/thesis/lib/python3.9/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_5640/3369351507.py in <module>
      9 formats = ["list-order", "list-boolean", "list-count", "tensor-count"]
     10 
---> 11 timings = [
     12     (time_convert_triplet(triplets, to_format),
     13      f"{from_format}->{to_format}")

/tmp/ipykernel_5640/3369351507.py in <listcomp>(.0)
     10 
     11 timings = [
---> 12     (time_convert_triplet(triplets, to_format),
     13      f"{from_format}->{to_format}")
     14     for from_format, triplets in zip(formats, data)

/tmp/ipykernel_5640/3369351507.py in time_convert_triplet(triplets, to_format)
      1 def time_convert_triplet(triplets, to_format):
      2     time_start = time.process_time()
----> 3     check_query_response(triplets, result_format=to_format)
      4     return (time.process_time() - time_start)
      5 

~/thesis/cblearn/cblearn/utils/_validate_data.py in check_query_response(query, response, result_format, standard)
    290             query = check_tensor_query_response(query, (QueryFormat.TENSOR, input_response_format), standard=False)
    291             query, response = query.coords.T, query.data
--> 292         return check_list_query_response(query, response, (output_query_format, output_response_format),
    293                                          standard=standard)

~/thesis/cblearn/cblearn/utils/_validate_data.py in check_list_query_response(query, response, result_format, standard)
    133 
    134     if response_format is ResponseFormat.ORDER:
--> 135         return check_order_list_query_response(query, response)
    136     elif response_format is ResponseFormat.BOOLEAN:
    137         return check_bool_list_query_response(query, response, standard=standard)

~/thesis/cblearn/cblearn/utils/_validate_data.py in check_order_list_query_response(query, response)
     94 
     95 def check_order_list_query_response(query, response):
---> 96     query, response = _check_list_query_response(query, response)
     97     __, input_response_format = data_format(query, response)
     98 

~/thesis/cblearn/cblearn/utils/_validate_data.py in _check_list_query_response(query, response)
     13 def _check_list_query_response(query, response):
     14     if response is None:
---> 15         return check_array(query, dtype=np.uint32), None
     16     else:
     17         return check_X_y(query, response, dtype=np.uint32)

~/miniconda3/envs/thesis/lib/python3.9/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~/miniconda3/envs/thesis/lib/python3.9/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    665                     # inf (numpy#14412). We cannot use casting='safe' because
    666                     # then conversion float -> int would be disallowed.
--> 667                     array = np.asarray(array, order=order)
    668                     if array.dtype.kind == 'f':
    669                         _assert_all_finite(array, allow_nan=False,

~/miniconda3/envs/thesis/lib/python3.9/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order, like)
    100         return _asarray_with_like(a, dtype=dtype, order=order, like=like)
    101 
--> 102     return array(a, dtype, copy=False, order=order)
    103 
    104 

ValueError: could not broadcast input array from shape (1000000,3) into shape (1000000,)

</code></pre>

**Comment by dekuenstle** [comment]
We will restructure the triplet format api, #35, and should afterwards fix this example.
